name: Build and deploy to Azure Static Web Apps (Production)

on:
  push:
    branches:
      - main  # Trigger on push to 'main' branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Azure Static Web App
        uses: azure/static-web-apps-deploy@v1
        with:
          app_location: "/"  # The location of your app files, e.g., /index.html
          api_location: ""  # Leave empty if you don't have an API
          output_location: ""  # Optional: specify the build output folder if you have one
        env:
          AZURE_STATIC_WEB_APPS_API_TOKEN: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
