name: Build and Deploy to Azure Static Web Apps

on:
  push:
    branches:
      - main  # Trigger deployment on push to main branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: 'Set up Azure Static Web Apps'
        uses: azure/static-web-apps-deploy@v1
        with:
          app_location: '/'  # Point to the root directory if index.html is there
          api_location: ''   # Leave empty since you're not using Azure Functions
          output_location: '' # No output needed
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}  # Set your secret token
